version: "3"

services:

  smartide-docs:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-go-opvscode:latest
    restart: always
    environment:
      ROOT_PASSWORD: root123
    volumes:
      - code:/home/project
    expose:
      - 1313
    ports:
      - 1313:1313
    networks:
      - smartide-network

networks:
  smartide-network:
    external: true

volumes:
  code:
    driver_opts:
      type: none
      device: ./.ide/
      o: bind