---

apiVersion: v1
kind: Pod
metadata:
  name: smartide-dev
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    workspace.service: smartide
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: smartide-dev
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vscode:latest
    command: ["/sbin/init"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "500m"
    ports:
      - containerPort: 22
      - containerPort: 3000
      - containerPort: 1313

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-dev
spec:
  ports:
    - name: "tools-ssh-6822"
      port: 6822
      targetPort: 22
    - name: "tools-webide-vscode-6800"
      port: 6800
      targetPort: 3000
    - name: "apps-hugo-website-1313"
      port: 1313
      targetPort: 1313
  selector:
    workspace.service: smartide
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide/smartide-network: "true"