version: "3"

networks:
  smartide-server-network:
    driver: bridge

services:
  web:
    image: ${SMARTIDE-SERVER-WEB-IMAGE}
    container_name: gva-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
     - smartide-server-network

  server:
    image: ${SMARTIDE-SERVER-API-IMAGE}
    container_name: gva-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - mysql
      - redis
    networks:
     - smartide-server-network

  mysql:
    image: ${SMARTIDE-SERVER-MYSQL-IMAGE}
    container_name: gva-mysql
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$(SMARTIDE-MYSQL-PASSWORD) --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 16
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'qmPlus' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '$(SMARTIDE-MYSQL-PASSWORD)' # root管理员用户密码
    networks:
     - smartide-server-network

  redis:
    image: ${SMARTIDE-SERVER-REDIS-IMAGE}
    container_name: gva-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    networks:
     - smartide-server-network

  myadmin:
    image: ${SMARTIDE-PHPMYADMIN-IMAGE}
    container_name: gva-myadmin # 容器名
    environment:
       PMA_HOST: 'gva-mysql'
    restart: always
    ports:
      - '8090:80'
    networks:
     - smartide-server-network
  portainer:
    image: ${SMARTIDE-PROTAINER-IMAGE}
    container_name: gva-portainer # 容器名
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    networks:
     - smartide-server-network
